NUMBER_OF_MONITORS = 2
# PV Names
PV_NAME_RANK0 = 'BPM'
PV_NAME_RANK1 = 'MONITOR'

# Network
HOST_ADDR = '127.0.0.1'
HOST_PORT = 8000
RPI_ADDR = '10.1.30.202'

# CAPROTOCOL
REQUEST_NOTHING = 0
REQUEST_STATUS = 1
REQUEST_GO_UP = 2
REQUEST_GO_DOWN = 3

# ACTUATOR
ACTUATOR_TIME_LIMIT = 5.0
ACTUATOR_UP = 1
ACTUATOR_DOWN = 2
ACTUATOR_GOES_UP = 3
ACTUATOR_GOES_DOWN = 4
ACTUATOR_ERROR = -1

# SWITCH
SWITCH_ON = 1
SWITCH_OFF = 0
SWITCH_ERROR = -1

# GPIO MAP
GPIO_MAP = {f'{PV_NAME_RANK1}0':{'RELAY':22, 'UPPER_SWITCH':17, 'LOWER_SWITCH':27},
            f'{PV_NAME_RANK1}1':{'RELAY':26, 'UPPER_SWITCH':13, 'LOWER_SWITCH':19}}