NUMBER_OF_MONITORS = 1

# Network
HOST_ADDR = '127.0.0.1'
HOST_PORT = 8000

# CAPROTOCOL
REQUEST_NOTHING = 0
REQUEST_STATUS = 1
REQUEST_GO_UP = 2
REQUEST_GO_DOWN = 3
REQUEST_ERROR = -1

# ACTUATOR
ACTUATOR_TIME_LIMIT = 5.0
ACTUATOR_UP = 1
ACTUATOR_DOWN = 2
ACTUATOR_GOES_UP = 3
ACTUATOR_GOES_DOWN = 4
ACTUATOR_ERROR = -1

# GPIO
RELAY = 19
UPPER_SWITCH = 17
LOWER_SWITCH = 27

SWITCH_ON = 11
SWITCH_OFF = 10
SWITCH_ERROR = -11