# Network
HOST_ADDR = '127.0.0.1'
HOST_PORT = 8000

# ACTUATOR
ACTUATOR_TIME_LIMIT = 5.0
ACTUATOR_UP = 0
ACTUATOR_DOWN = 2
ACTUATOR_GOES_UP = 3
ACTUATOR_GOES_DOWN = 4
ACTUATOR_ERROR = -1

# GPIO
RELAY = 19
UPPER_SWITCH = 17
LOWER_SWITCH = 27

SWITCH_ON = 11
SWITCH_OFF = 10
SWITCH_ERROR = -11